CREATE DATABASE TheMentalist

USE TheMentalist

DROP TABLE FUNCIONARIO
CREATE TABLE FUNCIONARIO(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(50) NOT NULL,
SEXO VARCHAR(9) NOT NULL,
SALARIO NUMERIC(7,2) NOT NULL,
RG VARCHAR(12) NOT NULL,
CPF VARCHAR(14) NOT NULL,
CEP VARCHAR(9) NOT NULL,
RUA VARCHAR(80) NOT NULL,
COMPLEMENTO VARCHAR(50) NOT NULL,
CIDADE VARCHAR(25) NOT NULL,
UF VARCHAR(2) NOT NULL,
DTNASC VARCHAR(10) NOT NULL,
DTCAD DATETIME NOT NULL,
CARGO VARCHAR(20) NOT NULL,
CRP VARCHAR(30),
TELEFONE VARCHAR(14) NOT NULL,
CELULAR VARCHAR(15) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
USUARIO VARCHAR(40) ,
SENHA VARCHAR(30),
HENTRADA VARCHAR(10),
HSAIDA VARCHAR(10),
OBSERVACAO VARCHAR(200),
)

SELECT * FROM FUNCIONARIO;
 
INSERT INTO FUNCIONARIO (NOME, RG, CPF, CIDADE, ENDERECO, UF, DTNASC, DTCAD, CARGO, CRP, TELEFONE, CELULAR, EMAIL, USUARIO, SENHA, HENTRADA, HSAIDA)
VALUES ('VENANCIO', '50550778X', '123456789', 'SAO PAULO','RUA', 'SP', '16/04/1996', '07/09/2013','Psicólogo','1212', '35966257', '76767676', 'VE@VE', 'VENANCIO', 'LINDO', '12:12', '12:13')

UPDATE FUNCIONARIO SET DTNASC='16/01/989' WHERE ID=1


DROP TABLE PACIENTE

CREATE TABLE PACIENTE(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(50) NOT NULL,
SEXO VARCHAR(9) NOT NULL,
RG VARCHAR(12) NOT NULL,
CPF VARCHAR(14) NOT NULL,
PAI VARCHAR(50) NOT NULL,
MAE VARCHAR(50) NOT NULL,
EC VARCHAR(20) NOT NULL,
CIDADE VARCHAR(25) NOT NULL,
UF VARCHAR(2) NOT NULL,
CEP VARCHAR(9) NOT NULL,
RUA VARCHAR(80) NOT NULL,
COMPLEMENTO VARCHAR(50) NOT NULL,
MEDICACAO VARCHAR(50),
DTNASC VARCHAR(10) NOT NULL,
DTCAD DATETIME NOT NULL,
OBSERVACAO VARCHAR(500) NOT NULL,
RESPONSAVEL VARCHAR(50),
TELEFONERES VARCHAR(15),
TELEFONE VARCHAR(14) NOT NULL,
CELULAR VARCHAR(15) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,

)

SELECT * FROM PACIENTE
drop table CONSULTA

CREATE TABLE CONSULTA(
ID INT PRIMARY KEY IDENTITY,
ID_FUNCIONARIO INT NOT NULL,
ID_PACIENTE INT NOT NULL ,
DESCRICAO VARCHAR(500),
VALOR NUMERIC(6,2),
DATA DATETIME ,
HORARIO DATETIME  , 
STATUS VARCHAR(10) NOT NULL ,
FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID), 
FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTE(ID), 
)
SELECT * FROM CONSULTA
drop table ANOTACAO

CREATE TABLE ANOTACAO(
ID INT PRIMARY KEY IDENTITY,
ID_CONSULTA INT NOT NULL,
ANOTACAO VARCHAR(999),
FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTA(ID),
)

SELECT * FROM ANOTACAO
